language: csharp

solution: Authentication.sln

sudo: true

mono:
  - 4.2.1

addons:
  apt:
    packages:
    - gtk-sharp2
    - mono-dbg

install:
  - nuget restore Authentication.sln
  - nuget install NUnit.Console -Version 3.6.0 -OutputDirectory target
  - nuget install coveralls.net -Version 0.7.0 -OutputDirectory target
  - git clone --depth=50 git://github.com/csMACnz/monocov.git target/monocov
  - cp /usr/lib/mono/gac/Mono.Cecil/*/* target/monocov/
  - cd target/monocov
  - ./configure
  - make
  - sudo make install
  - cd ../..

script:
  - xbuild /p:Configuration=Release Authentication.sln
  - export LD_LIBRARY_PATH=/usr/local/lib
  - mono --debug --profile=monocov:outfile=target/coverage.cov,+[MiraclAuthentication] ./target/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe --process=Single ./MiraclAuthenticationTests/bin/Release/MiraclAuthenticationTests.dll
  - monocov --export-xml=target/coverage target/coverage.cov

after_success:
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - mono ./target/coveralls.net.0.7.0/tools/csmacnz.Coveralls.exe --monocov --input target/coverage --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID --serviceName travis-ci --useRelativePaths

