version: '#{build}'
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: Ltsg9PfcfnGxy1zm98lPp8o49MSZdl7M5tkqgy0gW90tJySjQbsv1cVOWE9S3CFW
  OPENCOVER_VER: 4.6.519
  COVERALLS_NET_VER: 0.412
  COVERAGE_FILTER: +[MiraclAuthentication]* -[MiraclAuthenticationTests]* -[SampleWebApp]*
  COVERAGE_DIR: .\coverage
  OPENCOVER_EXE: '%COVERAGE_DIR%\OpenCover.%OPENCOVER_VER%\tools\OpenCover.Console.exe'
  COVERALLS_NET_EXE: '%COVERAGE_DIR%\coveralls.net.%COVERALLS_NET_VER%\tools\csmacnz.Coveralls.exe'
install:
- cmd: >-
    nuget install OpenCover -Version %OPENCOVER_VER% -OutputDirectory %COVERAGE_DIR%

    nuget install coveralls.net -Version %COVERALLS_NET_VER% -OutputDirectory %COVERAGE_DIR%
before_build:
- cmd: nuget restore
build:
  project: Authentication.sln
  verbosity: minimal
test_script:
- cmd: >-
    %OPENCOVER_EXE% -target:nunit3-console.exe -targetargs:".\MiraclAuthenticationTests\bin\Release\MiraclAuthenticationTests.dll" -filter:"%COVERAGE_FILTER%" -register:user -output:%COVERAGE_DIR%\coverage.xml

    %COVERALLS_NET_EXE% --opencover -i %COVERAGE_DIR%\coverage.xml