version: 1.0.{build}
image: Visual Studio 2019
build:
  verbosity: minimal

configuration: Release

environment:
  OPENCOVER_VER: 4.6.519
  COVERALLS_NET_VER: 0.412
  COVERAGE_FILTER: +[MiraclAuthentication]* -[MiraclAuthenticationTests]* -[SampleWebApp]*
  COVERAGE_DIR: .\coverage
  OPENCOVER_EXE: '%COVERAGE_DIR%\OpenCover.%OPENCOVER_VER%\tools\OpenCover.Console.exe'
  COVERALLS_NET_EXE: '%COVERAGE_DIR%\coveralls.net.%COVERALLS_NET_VER%\tools\csmacnz.Coveralls.exe'
  COVERALLS_REPO_TOKEN:
    secure: QyuBtbDw4AphFDBkt4lqnp+CDFk8//Ehju7Lrc+2uN/lDre6lVzbFY5twYwvqVOc
  MFA_CLIENT_SECRET:
    secure: wA4diTt4R8MV83KvKB3yKstc0tSwqDj4GkgGLel0mD5RgLiki3AHGuphsij7DPSM
  MFA_CLIENT_ID:
    secure: GBtYioXxsZ8c5J0sgVz+gA==

init:
  - rmdir C:\cygwin /s /q
  - rmdir C:\QT /s /q

install:
  - cmd: |
      nuget install OpenCover -Version %OPENCOVER_VER% -OutputDirectory %COVERAGE_DIR%
      nuget install coveralls.net -Version %COVERALLS_NET_VER% -OutputDirectory %COVERAGE_DIR%

before_build:
  - cmd: nuget restore Authentication.sln -Verbosity quiet

build_script:
  cmd: msbuild /m /verbosity:minimal Authentication.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - cmd: |
      echo "THE TOKEN IS: "
      echo %COVERALLS_REPO_TOKEN%
      echo ${{ secrets.COVERALLS_REPO_TOKEN }}
      %OPENCOVER_EXE% -target:nunit3-console.exe -targetargs:".\MiraclAuthenticationTests\bin\Release\MiraclAuthenticationTests.dll" -filter:"%COVERAGE_FILTER%" -register:user -returntargetcode -output:%COVERAGE_DIR%\coverage.xml
      %COVERALLS_NET_EXE% --opencover -i %COVERAGE_DIR%\coverage.xml --serviceName appveyor --useRelativePaths --jobId %APPVEYOR_BUILD_NUMBER%
